# Generated by Django 6.0 on 2025-12-17 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='e_image',
            field=models.ImageField(default=2, upload_to='employees/'),
            preserve_default=False,
        ),
    ]
